@startuml
|Клиент|
start
:Регистрация/авторизация;
|Система|
:Подтверждение учётных данных;

|Клиент|
:Выбор товаров;
:Добавление в корзину;
:Оформление заказа;
:Выбор способа доставки и оплаты;

|Система|
:Проверка наличия товара;

if (Товар доступен?) then (да)
  :Применить промо-код/скидки;
  if (Скидка применима?) then (да)
    :Обновить сумму заказа;
  else (нет)
    :Уведомить об ошибке скидки;
  endif
  
  fork
    |Оплата|
    :Проверка платёжных данных;
    :Выполнение транзакции;
    
    if (Оплата успешна?) then (да)
      :Зафиксировать оплату;
    else (нет)
    |Обработка проблем оплаты|
      :Уведомление клиента;
      :Предложить альтернативные способы;
      
      if (Клиент устранил проблему?) then (да)
        :Повторить оплату;
      else (нет)
        :Отменить заказ;
        if (Средства списаны?) then (да)
          :Вернуть средства;
        endif
        stop
      endif
    endif
  fork again
    |Склад|
    :Уведомление склада;
    :Комплектация заказа;
  end fork
  
  |Система|
  if (Оплата успешна AND Товар готов?) then (да)
    :Генерация счёт-фактуры;
    :Отправка подтверждения;
    :Обновить статус "Отправлен";
    
    |Клиент|
    :Отслеживание заказа;
    :Получение уведомлений;
    stop
  else (нет)
    :Приостановить обработку;
  endif
  
else (нет) 
 |Обработка отсутствия товара|
  :Уведомить клиента;
  
  fork
    :Предложить альтернативный товар;
  fork again
    :Предложить ожидание поступления;
  end fork
  
  if (Клиент выбрал решение?) then (да)
    if (Выбрана альтернатива?) then (да)
      :Обновить заказ;
      detach
    else (Ожидание)
      :Уведомить о поступлении;
      detach
    endif
  else (нет)
    :Отменить заказ;
    stop
  endif
endif

@enduml